Controllers/KullaniciController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Ahtapot_Recipe.Models;
using Ahtapot_Recipe.ViewModel;

namespace Ahtapot_Recipe.Controllers;

public class KullaniciController : Controller
{
	private readonly ILogger<KullaniciController> _logger;

	public KullaniciController(ILogger<KullaniciController> logger)
	{
		_logger = logger;
	}

	public IActionResult Index()
	{
		return View();
	}
	public IActionResult Anasayfa()
	{
		return View();
	}
	public IActionResult Hakkimizda()
	{
		return View();
	}
	public IActionResult Iletisim()
	{
		return View();
	}
	public IActionResult Ekle()
	{
		return View();
	}


	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult Post([FromForm] KullaniciModel model)
	{
		using (var db = new YemekDbContext())
		{
			db.Kullanici.Add(model);
			db.SaveChanges();
			return Content("Kullanıcı başarıyla kaydedildi.");
		}
	}

	public IActionResult Privacy()
	{
		return View();
	}
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult Login([FromForm] LoginViewModel model)
	{
		if (ModelState.IsValid)
		{
			using (var db = new YemekDbContext())
			{
				var kullanici = db.Kullanici.Where(t => t.Eposta == model.Eposta && t.Sifre == model.Sifre).ToList();
				if (kullanici.Any())
				{
					if (string.IsNullOrEmpty(HttpContext.Session.GetString("Isim")))
					{
						HttpContext.Session.SetString("Id", kullanici.FirstOrDefault().Id.ToString());
						HttpContext.Session.SetString("Isim", kullanici.FirstOrDefault().Isim.ToString());
					}
					TempData["Isim"] = HttpContext.Session.GetString("Isim").ToString();
					
					return RedirectToAction("Index","Home");
				}
				else
				{
					return Content("Giriş Yapılamadı. Eposta veya şifre yanlış.");
				}

			}
		}
		else
		{
			return Content("Hatalı format!");
		}


	}


}

Views/Kullanici/_Giris.cshtml
<div class="form-box login">
    <div class="form-details">
        <h2>Hoşgeldiniz</h2>
        <p style="font-size: 15px">Enfes yemek tariflerine ulaşmak için giriş yapın.</p>
    </div>
    <div class="form-content">
        <h2>GİRİŞ YAP</h2>
        @using (Html.BeginForm("Login", "Kullanici", FormMethod.Post))
        {
        @model Ahtapot_Recipe.ViewModel.LoginViewModel;
            <div class="input-field">
                @Html.EditorFor(m => m.Eposta)
                <label>Email</label>
            </div>
            <div class="input-field">
                @Html.EditorFor(m => m.Sifre)
                <label>Şifre</label>
            </div>
            <a href="Navbar/Iletisim" class="forgot-pass-link">Şifrenizi mi unuttunuz?</a>
            <button type="submit">Giriş Yap</button>
        }
        <div class="bottom-link">
            Hesabınız yok mu?
            <a href="#" id="signup-link">Kayıt Ol</a>
        </div>
    </div>
</div>

Views/Kullanici/_Kayit.cshtml
<div class="form-box signup">
            <div class="form-details">
                <h2>Hesap Oluştur</h2>
                <p>Yemek Tariflerine ulaşmak için kayıt olun.</p>
            </div>
            <div class="form-content">
                <h2>KAYIT OL</h2>
                @using (Html.BeginForm("Post", "Kullanici", FormMethod.Post))
                {
                    @model Ahtapot_Recipe.Models.KullaniciModel;
                    @Html.HiddenFor(m => m.Id)
                    <div class="input-field">
                        @Html.EditorFor(m => m.Isim)
                        <label>İsim girin</label>
                    </div>
                    <div class="input-field">
                        @Html.EditorFor(m => m.Soyisim)
                        <label>Soyisim girin</label>
                    </div>
                    <div class="input-field">
                        @Html.EditorFor(m => m.Eposta)
                        <label>Email adresinizi girin</label>
                    </div>
                    <div class="input-field">
                        @Html.EditorFor(m => m.Sifre)
                        <label>Şifre oluşturun</label>
                    </div>
                    @* <div class="policy-text">
                        <input type="checkbox" id="policy">
                        <label for="policy">
                            Okudum ve kabul ediyorum
                            <a href="#" class="option">Şartlar & Koşulları</a>
                        </label>
                    </div> *@
                    <button type="submit">Kayıt Ol</button>
                }
                <div class="bottom-link">
                    Hesabınız var mı?
                    <a href="#" id="login-link">Giriş Yap</a>
                </div>
            </div>
        </div>