Controllers/TarifController.cs
using Ahtapot_Recipe.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Http.Headers;

namespace Ahtapot_Recipe.Controllers;

public class TarifController : Controller
{
    private readonly ILogger<TarifController> _logger;

    public TarifController(ILogger<TarifController> logger)
    {
        _logger = logger;
    }
    public IActionResult Anasayfa()
    {
        return View();
    }
    public IActionResult Hakkimizda()
    {
        return View();
    }
    public IActionResult Iletisim()
    {
        return View();
    }
    public IActionResult Index()
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Id")))
        {
            using (var db = new YemekDbContext())
            {
                var tarif = db.Tarif.ToList();
                return View(tarif);
            }
        }
        return View();       
    }
    [HttpPost]
    public IActionResult YemekKaydet(TarifModel model, IFormFile file)
    {
        var dosyaIsimi = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (System.IO.Stream stream = new FileStream(path, FileMode.Create))
        {
            file.CopyToAsync(stream);
        }
         
        using (var db = new YemekDbContext())
        {
            model.OlusturulmaTarihi = System.DateTime.Now;
            model.Olusturan = 1;
            model.YemekFoto = dosyaIsimi;
            db.Tarif.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

    public IActionResult Ekle()
    {
        return View();
    }


    public IActionResult Duzenle(int id)
    {
        using (var db = new YemekDbContext())
        {
            var tarif = db.Tarif.Where(t => t.Id == id).FirstOrDefault();
            return View(tarif);
        }

    }


    [HttpPost]
    public IActionResult Duzenle(TarifModel model)
    {
        using (var db = new YemekDbContext())
        {
            db.Entry(model).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }


    public IActionResult Sil(int Id)
    {
        using (var db = new YemekDbContext())
        {
            var tarif = db.Tarif.Where(t => t.Id == Id).FirstOrDefault();
            if (tarif != null)
            {
                db.Remove(tarif);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }

    
    public IActionResult TarifSil(int id)
    {
        using (var db = new YemekDbContext())
        {
            var tarif = db.Tarif.Where(t => t.Id == id).FirstOrDefault();
            return View("Sil",tarif);
        }
    }

}

Views/Tarif/Duzenle.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
@{Layout=null;}
<title>Tarif Düzenle</title>
<style>
   

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Open Sans", sans-serif;
}

body {
    height: 100vh;
    width: 100%;
    background: url("images/hero-bg.jpg") center/cover no-repeat;
}

header {
    position: fixed;
    width: 100%;
    top: 0;
    left: 0;
    z-index: 10;
    padding: 0 10px;
}

.navbar {
    display: flex;
    padding: 22px 0;
    align-items: center;
    max-width: 1200px;
    margin: 0 auto;
    justify-content: space-between;
}

.navbar .hamburger-btn {
    display: none;
    color: #fff;
    cursor: pointer;
    font-size: 1.5rem;
}

.navbar .logo {
    gap: 10px;
    display: flex;
    align-items: center;
    text-decoration: none;
}

.navbar .logo img {
    width: 40px;
    border-radius: 50%;
}

.navbar .logo h2 {
    color: #fff;
    font-weight: 600;
    font-size: 1.7rem;
}

.navbar .links {
    display: flex;
    gap: 35px;
    list-style: none;
    align-items: center;
}

.navbar .close-btn {
    position: absolute;
    right: 20px;
    top: 20px;
    display: none;
    color: #000;
    cursor: pointer;
}

.navbar .links a {
    color: #fff;
    font-size: 1.1rem;
    font-weight: 500;
    text-decoration: none;
    transition: 0.1s ease;
}

.navbar .links a:hover {
    color: #19e8ff;
}

.navbar .login-btn {
    border: none;
    outline: none;
    background: #fff;
    color: #275360;
    font-size: 1rem;
    font-weight: 600;
    padding: 10px 18px;
    border-radius: 3px;
    cursor: pointer;
    transition: 0.15s ease;
}

.navbar .login-btn:hover {
    background: #ddd;
}

.form-popup {
    position: fixed;
    top: 50%;
    left: 50%;
    z-index: 10;
    width: 100%;
    opacity: 0;
    pointer-events: none;
    max-width: 720px;
    background: #fff;
    border: 2px solid #fff;
    transform: translate(-50%, -70%);
}

.show-popup .form-popup {
    opacity: 1;
    pointer-events: auto;
    transform: translate(-50%, -50%);
    transition: transform 0.3s ease, opacity 0.1s;
}

.form-popup .close-btn {
    position: absolute;
    top: 12px;
    right: 12px;
    color: #878484;
    cursor: pointer;
}

.blur-bg-overlay {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 10;
    height: 100%;
    width: 100%;
    opacity: 0;
    pointer-events: none;
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
    transition: 0.1s ease;
}

.show-popup .blur-bg-overlay {
    opacity: 1;
    pointer-events: auto;
}

.form-popup .form-box {
    display: flex;
}

.form-box .form-details {
    width: 100%;
    color: #fff;
    max-width: 330px;
    text-align: center;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.login .form-details {
    padding: 0 40px;
    background: url("images/login-img.jpg");
    background-position: center;
    background-size: cover;
}

.signup .form-details {
    padding: 0 20px;
    background: url("images/signup-img.jpg");
    background-position: center;
    background-size: cover;
}

.form-box .form-content {
    width: 100%;
    padding: 35px;
}

.form-box h2 {
    text-align: center;
    margin-bottom: 29px;
}

form .input-field {
    position: relative;
    height: 50px;
    width: 100%;
    margin-top: 20px;
}

.input-field input {
    height: 100%;
    width: 100%;
    background: none;
    outline: none;
    font-size: 0.95rem;
    padding: 0 15px;
    border: 1px solid #717171;
    border-radius: 3px;
}

.input-field input:focus {
    border: 1px solid #00bcd4;
}

.input-field label {
    position: absolute;
    top: 50%;
    left: 15px;
    transform: translateY(-50%);
    color: #4a4646;
    pointer-events: none;
    transition: 0.2s ease;
}

.input-field input:is(:focus, :valid) {
    padding: 16px 15px 0;
}

.input-field input:is(:focus, :valid)~label {
    transform: translateY(-120%);
    color: #00bcd4;
    font-size: 0.75rem;
}

.form-box a {
    color: #00bcd4;
    text-decoration: none;
}

.form-box a:hover {
    text-decoration: underline;
}

form :where(.forgot-pass-link, .policy-text) {
    display: inline-flex;
    margin-top: 13px;
    font-size: 0.95rem;
}

form button {
    width: 100%;
    color: #fff;
    border: none;
    outline: none;
    padding: 14px 0;
    font-size: 1rem;
    font-weight: 500;
    border-radius: 3px;
    cursor: pointer;
    margin: 25px 0;
    background: #00bcd4;
    transition: 0.2s ease;
}

form button:hover {
    background: #0097a7;
}

.form-content .bottom-link {
    text-align: center;
}

.form-popup .signup,
.form-popup.show-signup .login {
    display: none;
}

.form-popup.show-signup .signup {
    display: flex;
}

.signup .policy-text {
    display: flex;
    margin-top: 14px;
    align-items: center;
}

.signup .policy-text input {
    width: 14px;
    height: 14px;
    margin-right: 7px;
}



    .navbar {
        padding: 15px 0;
    }

    .navbar .logo img {
        display: none;
    }

    .navbar .logo h2 {
        font-size: 1.4rem;
    }

    .navbar .links {
        position: fixed;
        top: 0;
        z-index: 10;
        left: -100%;
        display: block;
        height: 100vh;
        width: 100%;
        padding-top: 60px;
        text-align: center;
        background: #fff;
        transition: 0.2s ease;
    }

    .navbar .links.show-menu {
        left: 0;
    }

    .navbar .links a {
        display: inline-flex;
        margin: 20px 0;
        font-size: 1.2rem;
        color: #000;
    }

    .navbar .links a:hover {
        color: #00BCD4;
    }

    .navbar .login-btn {
        font-size: 0.9rem;
        padding: 7px 10px;
    }
}


    .form-box .form-details {
        display: none;
    }

    .form-box .form-content {
        padding: 30px 20px;
    }
}
</style>
<div class="form-content">
    <h2>TARİF DÜZENLE</h2>
    @using (Html.BeginForm("Duzenle", "Tarif", FormMethod.Post))
        {
        @model Ahtapot_Recipe.Models.TarifModel;
        @Html.HiddenFor(m => m.OlusturulmaTarihi)
        @Html.HiddenFor(m => m.Olusturan)
        @Html.HiddenFor(m => m.YemekFoto)                      

        <div class="input-field">
            @Html.EditorFor(m => m.Id)
            <label>Yemek Id girin</label>
        </div>
        <div class="input-field">
            @Html.EditorFor(m => m.YemekAdi)
            <label>Yemek Adı girin</label>
        </div>
        <div class="input-field">
            @Html.EditorFor(m => m.Malzemeler)
            <label>Malzemeleri girin</label>
        </div>
        <div class="input-field">
            @Html.EditorFor(m => m.Yapilisi)
            <label>Yapılışını girin</label>
        </div>
        <div class="input-field">
             <button style="background-color: red;" type="submit">Tarifi Düzenle</button>
        </div>
        
        
        
   }
        
</div>

Views/Tarif/Ekle.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
@{Layout=null;}
<title>Tarif Ekle</title>
<style>
   

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Open Sans", sans-serif;
}

body {
    height: 100vh;
    width: 100%;
    background: url("images/hero-bg.jpg") center/cover no-repeat;
}

header {
    position: fixed;
    width: 100%;
    top: 0;
    left: 0;
    z-index: 10;
    padding: 0 10px;
}

.navbar {
    display: flex;
    padding: 22px 0;
    align-items: center;
    max-width: 1200px;
    margin: 0 auto;
    justify-content: space-between;
}

.navbar .hamburger-btn {
    display: none;
    color: #fff;
    cursor: pointer;
    font-size: 1.5rem;
}

.navbar .logo {
    gap: 10px;
    display: flex;
    align-items: center;
    text-decoration: none;
}

.navbar .logo img {
    width: 40px;
    border-radius: 50%;
}

.navbar .logo h2 {
    color: #fff;
    font-weight: 600;
    font-size: 1.7rem;
}

.navbar .links {
    display: flex;
    gap: 35px;
    list-style: none;
    align-items: center;
}

.navbar .close-btn {
    position: absolute;
    right: 20px;
    top: 20px;
    display: none;
    color: #000;
    cursor: pointer;
}

.navbar .links a {
    color: #fff;
    font-size: 1.1rem;
    font-weight: 500;
    text-decoration: none;
    transition: 0.1s ease;
}

.navbar .links a:hover {
    color: #19e8ff;
}

.navbar .login-btn {
    border: none;
    outline: none;
    background: #fff;
    color: #275360;
    font-size: 1rem;
    font-weight: 600;
    padding: 10px 18px;
    border-radius: 3px;
    cursor: pointer;
    transition: 0.15s ease;
}

.navbar .login-btn:hover {
    background: #ddd;
}

.form-popup {
    position: fixed;
    top: 50%;
    left: 50%;
    z-index: 10;
    width: 100%;
    opacity: 0;
    pointer-events: none;
    max-width: 720px;
    background: #fff;
    border: 2px solid #fff;
    transform: translate(-50%, -70%);
}

.show-popup .form-popup {
    opacity: 1;
    pointer-events: auto;
    transform: translate(-50%, -50%);
    transition: transform 0.3s ease, opacity 0.1s;
}

.form-popup .close-btn {
    position: absolute;
    top: 12px;
    right: 12px;
    color: #878484;
    cursor: pointer;
}

.blur-bg-overlay {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 10;
    height: 100%;
    width: 100%;
    opacity: 0;
    pointer-events: none;
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
    transition: 0.1s ease;
}

.show-popup .blur-bg-overlay {
    opacity: 1;
    pointer-events: auto;
}

.form-popup .form-box {
    display: flex;
}

.form-box .form-details {
    width: 100%;
    color: #fff;
    max-width: 330px;
    text-align: center;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.login .form-details {
    padding: 0 40px;
    background: url("images/login-img.jpg");
    background-position: center;
    background-size: cover;
}

.signup .form-details {
    padding: 0 20px;
    background: url("images/signup-img.jpg");
    background-position: center;
    background-size: cover;
}

.form-box .form-content {
    width: 100%;
    padding: 35px;
}

.form-box h2 {
    text-align: center;
    margin-bottom: 29px;
}

form .input-field {
    position: relative;
    height: 50px;
    width: 100%;
    margin-top: 20px;
}

.input-field input {
    height: 100%;
    width: 100%;
    background: none;
    outline: none;
    font-size: 0.95rem;
    padding: 0 15px;
    border: 1px solid #717171;
    border-radius: 3px;
}

.input-field input:focus {
    border: 1px solid #00bcd4;
}

.input-field label {
    position: absolute;
    top: 50%;
    left: 15px;
    transform: translateY(-50%);
    color: #4a4646;
    pointer-events: none;
    transition: 0.2s ease;
}

.input-field input:is(:focus, :valid) {
    padding: 16px 15px 0;
}

.input-field input:is(:focus, :valid)~label {
    transform: translateY(-120%);
    color: #00bcd4;
    font-size: 0.75rem;
}

.form-box a {
    color: #00bcd4;
    text-decoration: none;
}

.form-box a:hover {
    text-decoration: underline;
}

form :where(.forgot-pass-link, .policy-text) {
    display: inline-flex;
    margin-top: 13px;
    font-size: 0.95rem;
}

form button {
    width: 100%;
    color: #fff;
    border: none;
    outline: none;
    padding: 14px 0;
    font-size: 1rem;
    font-weight: 500;
    border-radius: 3px;
    cursor: pointer;
    margin: 25px 0;
    background: #00bcd4;
    transition: 0.2s ease;
}

form button:hover {
    background: #0097a7;
}

.form-content .bottom-link {
    text-align: center;
}

.form-popup .signup,
.form-popup.show-signup .login {
    display: none;
}

.form-popup.show-signup .signup {
    display: flex;
}

.signup .policy-text {
    display: flex;
    margin-top: 14px;
    align-items: center;
}

.signup .policy-text input {
    width: 14px;
    height: 14px;
    margin-right: 7px;
}



    .navbar {
        padding: 15px 0;
    }

    .navbar .logo img {
        display: none;
    }

    .navbar .logo h2 {
        font-size: 1.4rem;
    }

    .navbar .links {
        position: fixed;
        top: 0;
        z-index: 10;
        left: -100%;
        display: block;
        height: 100vh;
        width: 100%;
        padding-top: 60px;
        text-align: center;
        background: #fff;
        transition: 0.2s ease;
    }

    .navbar .links.show-menu {
        left: 0;
    }

    .navbar .links a {
        display: inline-flex;
        margin: 20px 0;
        font-size: 1.2rem;
        color: #000;
    }

    .navbar .links a:hover {
        color: #00BCD4;
    }

    .navbar .login-btn {
        font-size: 0.9rem;
        padding: 7px 10px;
    }
}


    .form-box .form-details {
        display: none;
    }

    .form-box .form-content {
        padding: 30px 20px;
    }
}
</style>
<div class="form-content">
    <h2>TARİF EKLE</h2>
    @using (Html.BeginForm("YemekKaydet", "Tarif", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        @model Ahtapot_Recipe.Models.TarifModel;
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.OlusturulmaTarihi)
        @Html.HiddenFor(m => m.Olusturan)                   

        <div class="input-field">
            @Html.EditorFor(m => m.YemekAdi)
            <label>Yemek Adı girin</label>
        </div>
        <div class="input-field">
            @Html.EditorFor(m => m.Malzemeler)
            <label>Malzemeleri girin</label>
        </div>
        <div class="input-field">
            @Html.EditorFor(m => m.Yapilisi)
            <label>Yapılışını girin</label>
        </div>
        <div class="input-field">
             <button style="background-color: red;" type="submit">Tarif Ekle</button>
        </div>
        
        <label for="file">Upload Image:</label> 
        <input type="file" name="file" id="file" style="width: 100%;" /> 
        
   }
        
</div>

Views/Tarif/Index.cshtml
<title>Tarifler</title>
@* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> *@
@{
	Layout = "~/Views/Shared/_LayoutAlternative.cshtml";
}
@model IEnumerable<Ahtapot_Recipe.Models.TarifModel>

<br><br><br><br>


<div class="list-group">
	@if (Model != null)
	{
	<div style="margin-top: auto;" class="btn-group" role="group" aria-label="Basic example">
		<a style="float: right" href="/Tarif/Ekle">
			<input type="button" class="btn btn-success" value="Tarif Ekle" />
		</a>
	</div>
		<br>

		<br>

		<br>

		<br>
		@foreach (var item in Model)
		{
			var hrefDetay = "/Tarif/TarifSil/" + @item.Id;
						<a href=@hrefDetay class="list-group-item list-group-item-action" aria-current="true">
							<div class="d-flex w-100 justify-content-between">
								<h5 style="font-size: 70px " class="mb-1">Yemek Adı: @item.YemekAdi.ToString()</h5>
								<small>Oluşturulma Tarihi: @item.OlusturulmaTarihi.ToString()</small>
							</div>
							<p style="font-size: 45px " class="mb-1">Yapılışı: @item.Yapilisi.ToString()</p>
							<small style="font-size: 30px ">Malzemeleri: @item.Malzemeler.ToString()</small>
				@{
					var href = "/Tarif/Duzenle/" + @item.Id;
				}

							<a href=@href>
								<input type="button" class="btn btn-success" value="Tarif Düzenle" />
							</a>
						</a>


		}
	}
	else
	{
			<div class="d-flex w-100 justify-content-between">
									<h5 style="font-size: 70px " class="mb-1">Lütfen Giriş Yapınız</h5>
									
								</div>
	}
</div>

Views/Tarif/Sil.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
@{
	Layout = null;
}
<title>Tarif Sil</title>
<style>


* {
	margin: 0;
	padding: 0;
	box-sizing: border-box;
	font-family: "Open Sans", sans-serif;
}

body {
	height: 100vh;
	width: 100%;
	background: url("images/hero-bg.jpg") center/cover no-repeat;
}

header {
	position: fixed;
	width: 100%;
	top: 0;
	left: 0;
	z-index: 10;
	padding: 0 10px;
}

.navbar {
	display: flex;
	padding: 22px 0;
	align-items: center;
	max-width: 1200px;
	margin: 0 auto;
	justify-content: space-between;
}

.navbar .hamburger-btn {
	display: none;
	color: #fff;
	cursor: pointer;
	font-size: 1.5rem;
}

.navbar .logo {
	gap: 10px;
	display: flex;
	align-items: center;
	text-decoration: none;
}

.navbar .logo img {
	width: 40px;
	border-radius: 50%;
}

.navbar .logo h2 {
	color: #fff;
	font-weight: 600;
	font-size: 1.7rem;
}

.navbar .links {
	display: flex;
	gap: 35px;
	list-style: none;
	align-items: center;
}

.navbar .close-btn {
	position: absolute;
	right: 20px;
	top: 20px;
	display: none;
	color: #000;
	cursor: pointer;
}

.navbar .links a {
	color: #fff;
	font-size: 1.1rem;
	font-weight: 500;
	text-decoration: none;
	transition: 0.1s ease;
}

.navbar .links a:hover {
	color: #19e8ff;
}

.navbar .login-btn {
	border: none;
	outline: none;
	background: #fff;
	color: #275360;
	font-size: 1rem;
	font-weight: 600;
	padding: 10px 18px;
	border-radius: 3px;
	cursor: pointer;
	transition: 0.15s ease;
}

.navbar .login-btn:hover {
	background: #ddd;
}

.form-popup {
	position: fixed;
	top: 50%;
	left: 50%;
	z-index: 10;
	width: 100%;
	opacity: 0;
	pointer-events: none;
	max-width: 720px;
	background: #fff;
	border: 2px solid #fff;
	transform: translate(-50%, -70%);
}

.show-popup .form-popup {
	opacity: 1;
	pointer-events: auto;
	transform: translate(-50%, -50%);
	transition: transform 0.3s ease, opacity 0.1s;
}

.form-popup .close-btn {
	position: absolute;
	top: 12px;
	right: 12px;
	color: #878484;
	cursor: pointer;
}

.blur-bg-overlay {
	position: fixed;
	top: 0;
	left: 0;
	z-index: 10;
	height: 100%;
	width: 100%;
	opacity: 0;
	pointer-events: none;
	backdrop-filter: blur(5px);
	-webkit-backdrop-filter: blur(5px);
	transition: 0.1s ease;
}

.show-popup .blur-bg-overlay {
	opacity: 1;
	pointer-events: auto;
}

.form-popup .form-box {
	display: flex;
}

.form-box .form-details {
	width: 100%;
	color: #fff;
	max-width: 330px;
	text-align: center;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
}

.login .form-details {
	padding: 0 40px;
	background: url("images/login-img.jpg");
	background-position: center;
	background-size: cover;
}

.signup .form-details {
	padding: 0 20px;
	background: url("images/signup-img.jpg");
	background-position: center;
	background-size: cover;
}

.form-box .form-content {
	width: 100%;
	padding: 35px;
}

.form-box h2 {
	text-align: center;
	margin-bottom: 29px;
}

form .input-field {
	position: relative;
	height: 50px;
	width: 100%;
	margin-top: 20px;
}

.input-field input {
	height: 100%;
	width: 100%;
	background: none;
	outline: none;
	font-size: 0.95rem;
	padding: 0 15px;
	border: 1px solid #717171;
	border-radius: 3px;
}

.input-field input:focus {
	border: 1px solid #00bcd4;
}

.input-field label {
	position: absolute;
	top: 50%;
	left: 15px;
	transform: translateY(-50%);
	color: #4a4646;
	pointer-events: none;
	transition: 0.2s ease;
}

.input-field input:is(:focus, :valid) {
	padding: 16px 15px 0;
}

.input-field input:is(:focus, :valid)~label {
	transform: translateY(-120%);
	color: #00bcd4;
	font-size: 0.75rem;
}

.form-box a {
	color: #00bcd4;
	text-decoration: none;
}

.form-box a:hover {
	text-decoration: underline;
}

form :where(.forgot-pass-link, .policy-text) {
	display: inline-flex;
	margin-top: 13px;
	font-size: 0.95rem;
}

form button {
	width: 100%;
	color: #fff;
	border: none;
	outline: none;
	padding: 14px 0;
	font-size: 1rem;
	font-weight: 500;
	border-radius: 3px;
	cursor: pointer;
	margin: 25px 0;
	background: #00bcd4;
	transition: 0.2s ease;
}

form button:hover {
	background: #0097a7;
}

.form-content .bottom-link {
	text-align: center;
}

.form-popup .signup,
.form-popup.show-signup .login {
	display: none;
}

.form-popup.show-signup .signup {
	display: flex;
}

.signup .policy-text {
	display: flex;
	margin-top: 14px;
	align-items: center;
}

.signup .policy-text input {
	width: 14px;
	height: 14px;
	margin-right: 7px;
}



	.navbar {
		padding: 15px 0;
	}

	.navbar .logo img {
		display: none;
	}

	.navbar .logo h2 {
		font-size: 1.4rem;
	}

	.navbar .links {
		position: fixed;
		top: 0;
		z-index: 10;
		left: -100%;
		display: block;
		height: 100vh;
		width: 100%;
		padding-top: 60px;
		text-align: center;
		background: #fff;
		transition: 0.2s ease;
	}

	.navbar .links.show-menu {
		left: 0;
	}

	.navbar .links a {
		display: inline-flex;
		margin: 20px 0;
		font-size: 1.2rem;
		color: #000;
	}

	.navbar .links a:hover {
		color: #00BCD4;
	}

	.navbar .login-btn {
		font-size: 0.9rem;
		padding: 7px 10px;
	}
}


	.form-box .form-details {
		display: none;
	}

	.form-box .form-content {
		padding: 30px 20px;
	}
}
</style>


<div class="form-content">
	<h2>TARİF SİL</h2>


		@model Ahtapot_Recipe.Models.TarifModel;
						<p>Aşağıdaki tarifi silmek istediğinize emin misiniz?</p>
						<br>					<br>

					<br>

	@Html.DisplayFor(m => m.Id)	<br />
	@Html.DisplayFor(m => m.YemekAdi)    <br />
	@Html.DisplayFor(m => m.Malzemeler)    <br />
	@Html.DisplayFor(m => m.Yapilisi)    <br />
	@Html.DisplayFor(m => m.OlusturulmaTarihi)

						<br />
	@using (Html.BeginForm("Sil", "Tarif", FormMethod.Post))
	{
		var href = "/Tarif/Sil/" + @Html.ValueFor(m => m.Id);
		<div class="input-field">
			 <a style="background-color: purple" href="@href" type="submit">Sil</a>
		</div>
	}
</div>